Add output if phoenix fails to start

diff --git a/shift-cluster b/shift-cluster
--- a/shift-cluster
+++ b/shift-cluster
@@ -247,6 +247,18 @@ start() {
     nohup ipfs daemon --enable-pubsub-experiment > ~/logs/ipfs.log 2>&1 &
     sleep 2
     nohup phoenix-cluster --bootstrap=$bootstrap_peers --config=$HOME/.phoenix/config.json start > ~/logs/phoenix-cluster.log 2>&1 &
+
+    sleep 2
+
+    netstat -tlnp 2>/dev/null | grep 2473 -q
+    if [ $? -ne 0 ] ; then
+        echo "Phoenix failed to start!"
+        echo ""
+        echo "Log output from ~/logs/phoenix-cluster.log:"
+        tail -n 20 ~/logs/phoenix-cluster.log
+        exit 1
+    fi
+
     echo "SHIFT cluster started"
 }
 
